Service Validator: "DateTime" property in odimra and plugin manager is not the valid date format - Bug fix
AngithCJ/ODIM pull request #1
Opened 2022-03-03 07:19 UTC by AngithCJ

**Changes**
- DateTime property format changed to as expected for odimra and plugin manager

**JIRA** : [BRUCE-5633](https://jira-pro.its.hpecorp.net:8443/browse/BRUCE-5633)

2022-03-03 07:21 UTC, irappa-pattar approved these changes

2022-03-03 07:23 UTC, shivacharanms commented
Add UT changes for the same.

2022-03-04 04:24 UTC, amar-shalgar approved these changes

2022-03-04 04:44 UTC, irappa-pattar approved these changes

2022-03-04 04:53 UTC, shivacharanms approved these changes

2022-03-04 05:12 UTC, hemkapoor approved these changes

2022-03-04 05:13 UTC, jeevan-kamkar approved these changes

2022-03-04 05:32 UTC, irappa-pattar requested changes

2022-03-04 05:32 UTC, irappa-pattar commented on svc-managers/managers/managers_test.go
>  	assert.Equal(t, "1.0", manager.FirmwareVersion, "Status code should be StatusOK.")
Could you please change the message in all assert.Equal
Ex. assert.Equal(t, "1.0", manager.FirmwareVersion, "**Firmware version should be 1.0**")

2022-03-04 05:58 UTC, AngithCJ commented on svc-managers/managers/managers_test.go
>  	assert.Equal(t, "1.0", manager.FirmwareVersion, "Status code should be StatusOK.")
I have updated the PR. Please review?

2022-03-04 05:58 UTC, irappa-pattar approved these changes
LGTM

2022-03-04 07:31 UTC, merged