BRUCE-5730 - Enable TLS based access for redis DB and test the working in one node setup
AngithCJ/ODIM pull request #10
Opened 2022-04-28 03:26 UTC by AngithCJ

**Changes**
- Added code for Redis connection establishment using tls authentication
- Added needed configuration in Redis master and slave configuration file
- Added odimra certificates volume in Redis pods.
- Enabled TLS authentication for Redis stream.
- Redis docker entry point scripts updated to connect using TLS.

2022-05-04 02:58 UTC, amar-shalgar approved these changes
LGTM

2022-05-11 11:28 UTC, shivacharanms requested changes

2022-05-11 11:28 UTC, shivacharanms commented on lib-messagebus/datacommunicator/redisstreamcomm.go
> +	tlsConfig.MinVersion = tls.VersionTLS12
use constants for tls version

2022-05-11 11:28 UTC, shivacharanms commented on lib-persistence-manager/persistencemgr/redis.go
> +		MinVersion:   tls.VersionTLS12,
use constants for tls version

2022-05-16 03:48 UTC, jeevan-kamkar approved these changes

2022-05-16 05:17 UTC, chauberahul1993 approved these changes

2022-05-16 06:38 UTC, shivacharanms approved these changes

2022-05-16 06:38 UTC, merged

2022-05-16 10:49 UTC, kavyamani596 approved these changes