As a developer I want to access redis DB with authentication
AngithCJ/ODIM pull request #12
Opened 2022-06-03 19:15 UTC by AngithCJ

**Changes**
- Redis password authentication enabled in Redis server deployment
- Redis DB connection updated to use the password in lib persistent manager
- Added logic to read the encrypted password from the deployment file and use 
it for Redis.
- Unit test updated
- Redis password authentication for GitHub.

Note: The changes in the PR include for the stories BRUCE-5355 and BRUCE-5875

2022-06-06 04:43 UTC, jeevan-kamkar approved these changes

2022-06-06 08:54 UTC, shivacharanms requested changes

2022-06-06 08:54 UTC, shivacharanms commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y update
Do not update explicitly

2022-06-06 08:54 UTC, shivacharanms commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y install build-essential libssl-dev openssl bash sed
What is the need for these packages? explain the need for each

2022-06-06 08:54 UTC, shivacharanms commented on install/Docker/dockerfiles/scripts/redis-checkdb.sh
> +redis_password=$(openssl pkeyutl -decrypt -in cipher -inkey ${ODIMRA_RSA_PRIVATE_FILE} -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256)
sha512 needs to be used. change across all references in PR

2022-06-06 08:54 UTC, shivacharanms commented on lib-utilities/config/config_test.go
> +				"RedisInMemoryPasswordFilePath": "/tmp/redis_inmemory_password",
Indentation needs to be fixed

2022-06-06 09:01 UTC, AngithCJ commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y update
Ok

2022-06-06 09:05 UTC, AngithCJ commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y install build-essential libssl-dev openssl bash sed
Need to install openssl, and build-essential and libssl-dev are dependency packages for that

2022-06-06 09:54 UTC, AngithCJ commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y update
As I cross checked, system can not locate openssl command without update command and build fail with the error 'can not locate openssl'

2022-06-06 09:55 UTC, AngithCJ commented on install/Docker/dockerfiles/Dockerfile.redis
> +RUN apt-get -y install build-essential libssl-dev openssl bash sed
This was mistake from my side, apparently build essential and libssl-dev is not needed for openssl. I will remove this

2022-06-07 03:37 UTC, amar-shalgar approved these changes

2022-06-07 11:28 UTC, shivacharanms approved these changes

2022-06-07 11:52 UTC, merged