Sprint 62 bruce 6721
AngithCJ/ODIM pull request #34
Opened 2022-10-31 05:13 UTC by AngithCJ

**Changes**

- Implemented a queue for tasks to perform update task operation

2022-10-31 06:47 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +func (p *ConnPool) GetWriteConnection() (*Conn, *errors.Error) {
we already have this method dont we?

2022-10-31 06:48 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +	if c.WriteConn == nil || c.WritePool == nil {
How is this handled upstream ?

2022-10-31 06:49 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
why discard if one json fails ? And why close the connection ?

2022-10-31 06:49 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
Same here

2022-10-31 06:51 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
Same here

2022-10-31 06:52 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis.go
> +	defer c.Close()
This is implicitly closign connection. The caller should close the connectio n .

2022-10-31 06:53 UTC, Bharath-KKB commented on lib-persistence-manager/persistencemgr/redis_test.go
> +type MockConn struct {
where do we actually test the DB connection codes ?

2022-10-31 06:54 UTC, Bharath-KKB commented on svc-task/main.go
> +	dbCommitInterval := time.Millisecond
This should not be hard coded

2022-10-31 06:56 UTC, Bharath-KKB commented on svc-task/thandle/thandle.go
> +	UpdateTaskStatusModel            func(t *tmodel.Task)
This updates the queue isnt it? So why name it model

2022-10-31 06:57 UTC, Bharath-KKB commented on svc-task/thandle/thandle.go
> -			err := ts.UpdateTaskStatusModel(subTask, common.InMemory)
who has reviewed previous commits?

2022-10-31 06:58 UTC, Bharath-KKB commented on svc-task/thandle/thandle.go
> +	ts.UpdateTaskStatusModel(childTask)
why is this not handling error ?

2022-10-31 07:00 UTC, Bharath-KKB commented on svc-task/tmessagebus/publish.go
> +		l.Log.Error("info: TaskURI:" + taskURI + ", EventID:" + eventID + ", MessageID:" + messageID)
Why is info: part of the message ??? Also should be one call to Log.Error

2022-10-31 07:03 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +func (p *ConnPool) GetWriteConnection() (*Conn, *errors.Error) {
No. We were retrieving the connection in each function.

2022-10-31 07:04 UTC, Bharath-KKB commented on svc-task/tmodel/tmodel.go
> +func ProcessTaskQueue(queue *chan *Task, tick *Tick) {
which code invokes this function? Why do we have to get DB pool/conn here ?

2022-10-31 07:08 UTC, Bharath-KKB commented on svc-task/tqueue/queue_test.go
> +func flushDB(t *testing.T) {
why are we doing this ? The tests are all mocks isnt it ?

2022-10-31 07:09 UTC, Bharath-KKB requested changes
Address comments

2022-10-31 07:10 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
can we avoid the error and continue with the other requests?

2022-10-31 07:11 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
This is probably a DB issue, right? Shouldn't we stop the execution here also?

2022-10-31 07:11 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +	defer c.Close()
Ok. will make the changes

2022-10-31 07:14 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis_test.go
> +type MockConn struct {
From here, I have added the tests https://github.com/AngithCJ/ODIM/pull/34/files#diff-771ec6af6c5d0e1d35ed5294a390a2ce8aa425a490080e9e250027c097fe296fR1453

2022-10-31 07:15 UTC, AngithCJ commented on svc-task/main.go
> +	dbCommitInterval := time.Millisecond
Ok.

2022-10-31 07:17 UTC, AngithCJ commented on svc-task/thandle/thandle.go
> +	UpdateTaskStatusModel            func(t *tmodel.Task)
This was the previous method. I did not change the name. I will make the changes.

2022-10-31 07:19 UTC, AngithCJ commented on svc-task/thandle/thandle.go
> +	ts.UpdateTaskStatusModel(childTask)
UpdateTaskStatusModel adds the task to the channel (queue). It does not return any error.

2022-10-31 07:22 UTC, AngithCJ commented on svc-task/tmessagebus/publish.go
> +		l.Log.Error("info: TaskURI:" + taskURI + ", EventID:" + eventID + ", MessageID:" + messageID)
It is a previous log that was outside of the if block. It was causing a lot of logs in the task service. I only moved that from outside to the if block to reduce the logs. I will remove the info from the log.

2022-10-31 07:26 UTC, AngithCJ commented on svc-task/tmodel/tmodel.go
> +func ProcessTaskQueue(queue *chan *Task, tick *Tick) {
It is called from here. https://github.com/AngithCJ/ODIM/pull/34/files#diff-18e3404157e24adfa7e24a951819248e66734e443863894985bd516245964e90R48

We are getting a DB pool in every service like this. I also needed to get DB conn here because I needed the same connection to start the pipeline, do the operation and commit the pipeline

2022-10-31 07:27 UTC, AngithCJ commented on svc-task/tqueue/queue_test.go
> +func flushDB(t *testing.T) {
No. The DB operations are not mocked.

2022-11-03 07:32 UTC, Shahid097 approved these changes

2022-11-03 08:06 UTC, sriteja-sabbineni approved these changes

2022-11-03 09:46 UTC, Bharath-KKB commented on svc-task/tmodel/tmodel.go
> +			saveID := table + ":" + task.ID
using integer(taskid) and not string(task URL) here will speed things up. As integer key hashing will be faster than strings. You can add the table and : before sending to DB.

2022-11-03 09:48 UTC, Bharath-KKB commented on svc-task/tmodel/tmodel.go
> +				if err.ErrNo() == errors.DBUpdateFailed {
check what is the error and recreate conn only if the original error is related to conn. In case of irrecoverable errors log the full data and return an error.

2022-11-03 09:50 UTC, Bharath-KKB commented on svc-task/tmodel/tmodel.go
> +		for i < maxRetry {
what if there is a set of tasks that were updated and some that didnt get updated ?

2022-11-03 09:51 UTC, Bharath-KKB requested changes
address comments shared earlier and those added in this PR

2022-11-03 17:09 UTC, kavyamani596 approved these changes

2022-11-04 06:00 UTC, amar-shalgar approved these changes

2022-11-04 06:05 UTC, AngithCJ commented on svc-task/tmodel/tmodel.go
> +			saveID := table + ":" + task.ID
task.ID is UUID. converting that to an integer will throw an error.

2022-11-04 06:08 UTC, AngithCJ commented on svc-task/tmodel/tmodel.go
> +				if err.ErrNo() == errors.DBUpdateFailed {
I have checked the library code and documentation. There the errors are not categorized. They are returning errors of error type.

2022-11-04 06:13 UTC, AngithCJ commented on svc-task/tmodel/tmodel.go
> +		for i < maxRetry {
Sorry If did not understand it correctly. we are committing the pipelined transaction after every task in the map is buffered to the pipe. So if any operation fails then we will discard the pipeline and try that whole batch again

2022-11-04 06:20 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +func (p *ConnPool) GetWriteConnection() (*Conn, *errors.Error) {
Made the changes as discussed in the call.

2022-11-04 06:22 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +	if c.WriteConn == nil || c.WritePool == nil {
This method is removed as we are sending tasks in a map now. Errors are handled as we discussed in the call.

2022-11-04 06:23 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
made the changes. if JSON marshal is failed it would be logged and continue the operation.

2022-11-04 06:26 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
Implemented retry to handle these errors. returning DB update failed error and once this error happens, I will be retrying the operation again.

2022-11-04 06:26 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +		c.WriteConn.Send("DISCARD")
did the same error handling here as well

2022-11-04 06:26 UTC, AngithCJ commented on lib-persistence-manager/persistencemgr/redis.go
> +	defer c.Close()
made the changes

2022-11-04 06:27 UTC, AngithCJ commented on svc-task/main.go
> +	dbCommitInterval := time.Millisecond
This is configured using odimra config

2022-11-04 06:28 UTC, AngithCJ commented on svc-task/thandle/thandle.go
> +	UpdateTaskStatusModel            func(t *tmodel.Task)
changed the name to UpdateTaskQueue

2022-11-04 06:28 UTC, AngithCJ commented on svc-task/tmessagebus/publish.go
> +		l.Log.Error("info: TaskURI:" + taskURI + ", EventID:" + eventID + ", MessageID:" + messageID)
made the changes

2022-11-04 06:39 UTC, AngithCJ commented on svc-task/tqueue/queue_test.go
> +func flushDB(t *testing.T) {
For the unit test, we are using a test DB and we are querying this DB to validate the operation. Here I have changed the unit test and DB was not needed for the test. So this function is removed.

2022-11-11 05:41 UTC, chauberahul1993 approved these changes

2022-11-14 14:08 UTC, amar-shalgar approved these changes

2022-11-14 14:09 UTC, merged