enable event service in case if the property set to false while adding server
AngithCJ/ODIM pull request #51
Opened 2023-06-19 13:39 UTC by AngithCJ

2023-06-19 14:19 UTC, chauberahul1993 approved these changes

2023-06-19 14:44 UTC, sriteja-sabbineni approved these changes

2023-06-19 15:28 UTC, jeevan-kamkar requested changes
Event service call shouldn't be called from aggregation service

2023-06-20 08:17 UTC, jeevan-kamkar approved these changes

2023-06-20 08:17 UTC, merged