Changed struct param names as preferred
AngithCJ/ODIM pull request #7
Opened 2022-03-16 15:12 UTC by AngithCJ

**Changes**
- Changed struct param names as preferred by go lint

2022-03-21 10:30 UTC, jeevan-kamkar requested changes
Address the requested change

2022-03-21 10:30 UTC, jeevan-kamkar commented on docs/README.md
> -    "HTTPPushURI": "",
remove the doc update

2022-03-21 10:30 UTC, jeevan-kamkar commented on svc-update/README.md
> -   "HTTPPushURI":"",
remove the doc update

2022-03-21 10:30 UTC, jeevan-kamkar commented on svc-update/uresponse/updateservice.go
>  	FirmwareInventory             FirmwareInventory         `json:"FirmwareInventory"`
json tag update in not required

2022-03-21 10:30 UTC, jeevan-kamkar commented on svc-update/uresponse/updateservice.go
> -	HTTPPushURITargetsBusy        bool                      `json:"HTTPPushURITargetsBusy,omitempty"`
check for the json tag update

2022-03-21 10:43 UTC, AngithCJ commented on docs/README.md
> -    "HTTPPushURI": "",
I changed HttpPushUri to HTTPPushURI in this [PR](https://github.com/AngithCJ/ODIM/pull/3). I am removing that changes here.

2022-03-21 10:43 UTC, AngithCJ commented on svc-update/README.md
> -   "HTTPPushURI":"",
same as above

2022-03-21 10:43 UTC, AngithCJ commented on svc-update/uresponse/updateservice.go
>  	FirmwareInventory             FirmwareInventory         `json:"FirmwareInventory"`
removing the tag update which was done in earlier PR

2022-03-21 10:43 UTC, AngithCJ commented on svc-update/uresponse/updateservice.go
> -	HTTPPushURITargetsBusy        bool                      `json:"HTTPPushURITargetsBusy,omitempty"`
same as above

2022-03-21 11:20 UTC, amar-shalgar approved these changes

2022-03-21 11:42 UTC, shivacharanms approved these changes

2022-03-22 05:34 UTC, jeevan-kamkar approved these changes

2022-03-22 05:57 UTC, merged